project:
  type: website
  output-dir: docs   # Crucial for GitHub Pages

website:
  title: "CHU9012"
  repo-url: https://github.com/aymeric-collart/CHU9012
  repo-actions: [issue]
  page-footer:
    left: "Â© 2026 Aymeric Collart"
    right: "This website is built with Quarto"

  # Top Navigation Bar
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - text: "Course Materials"
        href: course-materials/week1.qmd # Links to first week
      - text: "Assignments"
        menu:
          - assignments/hw1.qmd
    right:
      - icon: github
        href: https://github.com/aymeric-collart/CHU9012

  # Side Navigation Bar (Context aware)
  sidebar:
    - title: "Course Materials"
      contents:
        - section: "Part 1: Intro"
          contents:
            - text: "Week 1: Introduction"
              href: course-materials/week1.qmd
            - text: "Week 2: Linguistic research and ethics"
              href: course-materials/week2.qmd
            - text: "Week 3: Introduction"
              href: course-materials/week3.qmd
            - text: "Week 4: Linguistic researhc and ethics"
              href: course-materials/week4.qmd
            - text: "Week 5: Introduction"
              href: course-materials/week5.qmd
            - text: "Week 6: Linguistic researhc and ethics"
            - text: "Week 7: Introduction"
              href: course-materials/week7.qmd
            - text: "Week 8: Linguistic researhc and ethics"
              href: course-materials/week8.qmd
            - text: "Week 9: Introduction"
            - text: "Week 10: Linguistic researhc and ethics"
              href: course-materials/week10.qmd
            - text: "Week 11: Introduction"
              href: course-materials/week11.qmd
            - text: "Week 12: Linguistic researhc and ethics"
              href: course-materials/week12.qmd
            - text: "Week 13: Introduction"
              href: course-materials/week13.qmd
            - text: "Week 14: Linguistic researhc and ethics"
              href: course-materials/week14.qmd
            - text: "Week 15: Introduction"
            - text: "Week 16: Linguistic researhc and ethics"

format:
  html:
    theme:
      light: cosmo   # The theme for Light Mode
      dark: darkly   # The theme for Dark Mode (you can also use 'superhero' or 'cyborg')
    toc: true
    css: styles.css